name: warehouse
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cqrs: ^10.0.1
  cupertino_icons: ^1.0.2
  
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.4
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  json_annotation: ^4.8.1
  leancode_hooks: ^0.0.6
  mocktail: ^1.0.3
  provider: ^6.1.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter

  freezed: ^2.4.7
  go_router_builder: ^2.4.1
  json_serializable: ^6.5.4
  leancode_lint: ^8.0.0

flutter:
  uses-material-design: true
