name: warehouse
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cqrs: ^10.0.1
  cupertino_icons: ^1.0.2
  
  equatable: ^2.0.5
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.4
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  image_picker: ^1.0.7
  json_annotation: ^4.8.1
  leancode_cubit_utils:
    git:
      url: https://github.com/leancodepl/leancode_cubit_utils.git  
  leancode_forms: ^0.1.0
  leancode_hooks: ^0.0.6
  loading_overlay: ^0.3.0
  mocktail: ^1.0.3
  provider: ^6.1.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter

  freezed: ^2.4.7
  go_router_builder: ^2.4.1
  json_serializable: ^6.5.4
  leancode_lint: 8.0.0

flutter:
  uses-material-design: true
